language: python
python: 3.6
install:
  - pip install codecov
  - pip install pytest-cov
script:
  - pytest --cov=./ --cov-report=xml --cov-report=html 
  - codecov
after_success:
  - python request.py