version: "3"
services:
  python:
    image: codecov/standards-python:latest
    build: ./
    volumes: 
      - ./index.py:/app/index.py
      - ./test_index.py:/app/text_index.py
      - ./coverage.xml:/app/coverage.xml
    command: ./entrypoint.sh
volumes: 
  index.py:
  test_index.py:
  coverage.xml:
      

  
