name: Github Actions Python Standard
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test-and-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install pytest-cov
          pip install requests
      - name: Run Script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          CORRECT_COVERAGE: ${{ secrets.CORRECT_COVERAGE }}
        run: |
          pytest --cov=./ --cov-report=xml
          bash <(curl https://codecov.io/bash)
          cd src
          python request.py
          cd ..
      - name: Upstream to Standards
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        if: ${{ github.event_name == 'push'}}
        run: |
          ./upstream.sh
