name: Github Actions Python Standard

on: [push]
# on:
#   push:
#     branches:
#       - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install dependencies
        run: |
          pip install pytest-cov
          pip install requests
      - name: Run Script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          CORRECT_COVERAGE: "85.71429"
        run: |
          pytest --cov=./ --cov-report=xml
          bash <(curl https://codecov.io/bash)
          cd src
          python request.py
          cd ..
          ./upstream.sh
